# Displays available recipes by running `just -l`.
setup:
  #!/usr/bin/env bash
  just -l

i:
  bun install

test:
  #!/usr/bin/env bash
  just e2e-deploy
  go test ./...

e2e-deploy:
  #!/usr/bin/env bash
  bun run e2e_deploy.ts

run-trader *args:
  go run ./cmd/trader {{args}}

run-auto-trader *args:
  go run ./cmd/trader auto {{args}}

run-auto-localnet:
  go run ./cmd/trader auto --config auto-trader.localnet.json

run-auto-testnet:
  go run ./cmd/trader auto --config auto-trader.testnet.json 
