# Displays available recipes by running `just -l`.
setup:
  #!/usr/bin/env bash
  just -l

i:
  bun install

test:
  #!/usr/bin/env bash
  just e2e-deploy
  go test ./...

e2e-deploy:
  #!/usr/bin/env bash
  bun run e2e_deploy.ts
