# Options for analysis running. See https://golangci-lint.run/usage/configuration/ for config options.
run:
  timeout: 5m
issues:
  max-issues-per-linter: 0 # infinite
  max-same-issues: 0 # infinite
  fix: true
  exclude:
    # see https://github.com/stretchr/testify/issues/1199#issuecomment-1215592618, testify shows vet problem
    - 'github.com\/stretchr\/testify\/suite\.Suite contains sync\.RWMutex'
linters:
  enable:
    - whitespace
    - goimports
    - importas
  disable:
    - typecheck
linters-settings:
  misspell:
    locale: US
  goimports:
    # Put imports beginning with prefix after 3rd-party packages.
    # It's a comma-separated list of prefixes.
    local-prefixes: github.com/NibiruChain/nibiru
  revive:
    rules:
      - name: exported
        disabled: true
  importas:
    # no-unaliased: Forces the use of the specified alias
    no-unaliased: true
    # Disallows the use of aliases not specified by the linter.
    no-extra-aliases: false
    alias:
      - pkg: github.com/pkg/errors
        alias: pkgerrors
      - pkg: cosmossdk.io/errors
        alias: sdkioerrors
      - pkg: github.com/cosmos/cosmos-sdk/types/errors
        alias: sdkerrors
      - pkg: cosmossdk.io/math
        alias: sdkmath
      - pkg: github.com/cosmos/cosmos-sdk/types
        alias: sdk
      - pkg: github.com/cometbft/cometbft/rpc/core
        alias: cmtrpccoretypes
      - pkg: github.com/cometbft/cometbft/rpc/client
        alias: cmtrpcclient
      - pkg: github.com/cometbft/cometbft/config
        alias: cmtcfg
      - pkg: github.com/cometbft/cometbft/libs/cli
        alias: cmtcli
      - pkg: github.com/cometbft/cometbft/libs/rand
        alias: cmtrand
      - pkg: github.com/cometbft/cometbft/types
        alias: cmttypes

severity:
  default-severity: error
