project_name: nibid

env:
  - CGO_ENABLED=1

builds:
  - id: darwin
    main: ./cmd/nibid
    binary: nibid
    hooks:
      pre:
        - bash contrib/scripts/release_pre_darwin.sh
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CC=o64-clang
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=nibiru
      - -X github.com/cosmos/cosmos-sdk/version.AppName=nibid
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/types.DBBackend=rocksdb
      - -linkmode=external
      - -extldflags '-lrocksdb -lstdc++ -ldl -lz -lbz2'
    tags:
      - netgo
      - osusergo
      - ledger
      - static
      - static_wasm
      - rocksdb
      - pebbledb
      - grocksdb_no_link
    overrides:
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang

  - id: linux
    main: ./cmd/nibid
    binary: nibid
    hooks:
      pre:
        - bash contrib/scripts/release_pre_linux.sh
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/cosmos/cosmos-sdk/version.Name=nibiru
      - -X github.com/cosmos/cosmos-sdk/version.AppName=nibid
      - -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }}
      - -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }}
      - -X github.com/cosmos/cosmos-sdk/types.DBBackend=rocksdb
      - -linkmode=external
      - -extldflags '-static -lrocksdb -lstdc++ -lm -ldl -lpthread'
    tags:
      - netgo
      - osusergo
      - ledger
      - muslc
      - rocksdb
      - pebbledb
      - grocksdb_no_link
      - static
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc

universal_binaries:
  - id: darwin
