project_name: nibid

env:
  - CGO_ENABLED=1

builds:
  - id: darwin
    main: ./cmd/nibid
    binary: nibid
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    env:
      - CC=o64-clang
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/cosmos/cosmos-sdk/version.Name=nibiru -X github.com/cosmos/cosmos-sdk/version.AppName=nibid -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/tendermint/tendermint/version.TMCoreSemVer={{ .Env.TM_VERSION }}
      - -linkmode=external
    tags:
      - netgo
      - osusergo
      - ledger
      - static_build
      - static_wasm
    overrides:
      - goos: darwin
        goarch: arm64
        env:
          - CC=oa64-clang

  - id: linux
    main: ./cmd/nibid
    binary: nibid
    hooks:
      pre:
        - wget https://github.com/CosmWasm/wasmvm/releases/download/v1.1.1/libwasmvm_muslc.x86_64.a -O /usr/lib/x86_64-linux-gnu/libwasmvm_muslc.a
        - wget https://github.com/CosmWasm/wasmvm/releases/download/v1.1.1/libwasmvm_muslc.aarch64.a -O /usr/lib/aarch64-linux-gnu/libwasmvm_muslc.a
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CC=x86_64-linux-gnu-gcc
    flags:
      - -mod=readonly
      - -trimpath
    ldflags:
      - -s -w -X main.commit={{.Commit}} -X main.date={{ .CommitDate }} -X github.com/cosmos/cosmos-sdk/version.Name=nibiru -X github.com/cosmos/cosmos-sdk/version.AppName=nibid -X github.com/cosmos/cosmos-sdk/version.Version={{ .Version }} -X github.com/cosmos/cosmos-sdk/version.Commit={{ .Commit }} -X github.com/tendermint/tendermint/version.TMCoreSemVer={{ .Env.TM_VERSION }}
      - -linkmode=external
      - -extldflags '-Wl,-z,muldefs -static -lm'
    tags:
      - netgo
      - osusergo
      - ledger
      - muslc
      - static_build
    overrides:
      - goos: linux
        goarch: arm64
        env:
          - CC=aarch64-linux-gnu-gcc

universal_binaries:
  - id: darwin
