image: "gitpod/workspace-bun"

tasks:
  - name: "Install dependencies"
    before: |
      curl -L https://foundry.paradigm.xyz | bash
      source ~/.bashrc
      foundryup
    init: "bun install"

vscode:
  extensions:
    - "esbenp.prettier-vscode"
    - "NomicFoundation.hardhat-solidity"
