// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: perp/v1/state.proto

package types

import (
	fmt "fmt"
	github_com_cosmos_cosmos_sdk_types "github.com/cosmos/cosmos-sdk/types"
	types "github.com/cosmos/cosmos-sdk/types"
	_ "github.com/gogo/protobuf/gogoproto"
	proto "github.com/gogo/protobuf/proto"
	_ "github.com/regen-network/cosmos-proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type Side int32

const (
	Side_SIDE_UNSPECIFIED Side = 0
	Side_BUY              Side = 1
	Side_SELL             Side = 2
)

var Side_name = map[int32]string{
	0: "SIDE_UNSPECIFIED",
	1: "BUY",
	2: "SELL",
}

var Side_value = map[string]int32{
	"SIDE_UNSPECIFIED": 0,
	"BUY":              1,
	"SELL":             2,
}

func (x Side) String() string {
	return proto.EnumName(Side_name, int32(x))
}

func (Side) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{0}
}

type PnLCalcOption int32

const (
	PnLCalcOption_PNL_CALC_OPTION_UNSPECIFIED PnLCalcOption = 0
	PnLCalcOption_SPOT_PRICE                  PnLCalcOption = 1
	PnLCalcOption_TWAP                        PnLCalcOption = 2
	PnLCalcOption_ORACLE                      PnLCalcOption = 3
)

var PnLCalcOption_name = map[int32]string{
	0: "PNL_CALC_OPTION_UNSPECIFIED",
	1: "SPOT_PRICE",
	2: "TWAP",
	3: "ORACLE",
}

var PnLCalcOption_value = map[string]int32{
	"PNL_CALC_OPTION_UNSPECIFIED": 0,
	"SPOT_PRICE":                  1,
	"TWAP":                        2,
	"ORACLE":                      3,
}

func (x PnLCalcOption) String() string {
	return proto.EnumName(PnLCalcOption_name, int32(x))
}

func (PnLCalcOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{1}
}

type PnLPreferenceOption int32

const (
	PnLPreferenceOption_PNL_PREFERENCE_UNSPECIFIED PnLPreferenceOption = 0
	PnLPreferenceOption_MAX                        PnLPreferenceOption = 1
	PnLPreferenceOption_MIN                        PnLPreferenceOption = 2
)

var PnLPreferenceOption_name = map[int32]string{
	0: "PNL_PREFERENCE_UNSPECIFIED",
	1: "MAX",
	2: "MIN",
}

var PnLPreferenceOption_value = map[string]int32{
	"PNL_PREFERENCE_UNSPECIFIED": 0,
	"MAX":                        1,
	"MIN":                        2,
}

func (x PnLPreferenceOption) String() string {
	return proto.EnumName(PnLPreferenceOption_name, int32(x))
}

func (PnLPreferenceOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{2}
}

type MarginCalculationPriceOption int32

const (
	MarginCalculationPriceOption_MARGIN_CALCULATION_PRICE_OPTION_UNSPECIFIED MarginCalculationPriceOption = 0
	MarginCalculationPriceOption_SPOT                                        MarginCalculationPriceOption = 1
	MarginCalculationPriceOption_INDEX                                       MarginCalculationPriceOption = 2
	MarginCalculationPriceOption_MAX_PNL                                     MarginCalculationPriceOption = 3
)

var MarginCalculationPriceOption_name = map[int32]string{
	0: "MARGIN_CALCULATION_PRICE_OPTION_UNSPECIFIED",
	1: "SPOT",
	2: "INDEX",
	3: "MAX_PNL",
}

var MarginCalculationPriceOption_value = map[string]int32{
	"MARGIN_CALCULATION_PRICE_OPTION_UNSPECIFIED": 0,
	"SPOT":    1,
	"INDEX":   2,
	"MAX_PNL": 3,
}

func (x MarginCalculationPriceOption) String() string {
	return proto.EnumName(MarginCalculationPriceOption_name, int32(x))
}

func (MarginCalculationPriceOption) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{3}
}

type Params struct {
	// stopped identifies if the perp exchange is stopped or not
	Stopped                bool                                   `protobuf:"varint,1,opt,name=stopped,proto3" json:"stopped,omitempty"`
	MaintenanceMarginRatio github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=maintenance_margin_ratio,json=maintenanceMarginRatio,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"maintenance_margin_ratio"`
	// toll_ratio is the ratio transferred to the the fee pool
	TollRatio int64 `protobuf:"varint,3,opt,name=toll_ratio,json=tollRatio,proto3" json:"toll_ratio,omitempty"`
	// spread_ratio is the ratio transferred to the PerpEF.
	SpreadRatio int64 `protobuf:"varint,4,opt,name=spread_ratio,json=spreadRatio,proto3" json:"spread_ratio,omitempty"`
	// LiquidationFee is the percentage of liquidated position that will be given
	// to out as a reward. Half of the liquidation fee is given to the liquidator,
	// and the other half is given to the ecosystem fund.
	LiquidationFee int64 `protobuf:"varint,5,opt,name=liquidation_fee,json=liquidationFee,proto3" json:"liquidation_fee,omitempty"`
	// partial_liquidation_ratio is the share we try to liquidate if the margin is higher than liquidation fee
	PartialLiquidationRatio int64 `protobuf:"varint,6,opt,name=partial_liquidation_ratio,json=partialLiquidationRatio,proto3" json:"partial_liquidation_ratio,omitempty"`
}

func (m *Params) Reset()         { *m = Params{} }
func (m *Params) String() string { return proto.CompactTextString(m) }
func (*Params) ProtoMessage()    {}
func (*Params) Descriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{0}
}
func (m *Params) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Params) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Params.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Params) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Params.Merge(m, src)
}
func (m *Params) XXX_Size() int {
	return m.Size()
}
func (m *Params) XXX_DiscardUnknown() {
	xxx_messageInfo_Params.DiscardUnknown(m)
}

var xxx_messageInfo_Params proto.InternalMessageInfo

func (m *Params) GetStopped() bool {
	if m != nil {
		return m.Stopped
	}
	return false
}

func (m *Params) GetTollRatio() int64 {
	if m != nil {
		return m.TollRatio
	}
	return 0
}

func (m *Params) GetSpreadRatio() int64 {
	if m != nil {
		return m.SpreadRatio
	}
	return 0
}

func (m *Params) GetLiquidationFee() int64 {
	if m != nil {
		return m.LiquidationFee
	}
	return 0
}

func (m *Params) GetPartialLiquidationRatio() int64 {
	if m != nil {
		return m.PartialLiquidationRatio
	}
	return 0
}

// GenesisState defines the perp  module's genesis state.
type GenesisState struct {
	Params               Params            `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
	VaultBalance         []types.Coin      `protobuf:"bytes,2,rep,name=vault_balance,json=vaultBalance,proto3" json:"vault_balance" yaml:"module_account_balance"`
	PerpEfBalance        []types.Coin      `protobuf:"bytes,3,rep,name=perp_ef_balance,json=perpEfBalance,proto3" json:"perp_ef_balance" yaml:"module_account_balance"`
	FeePoolBalance       []types.Coin      `protobuf:"bytes,4,rep,name=fee_pool_balance,json=feePoolBalance,proto3" json:"fee_pool_balance" yaml:"module_account_balance"`
	PairMetadata         []*PairMetadata   `protobuf:"bytes,5,rep,name=pair_metadata,json=pairMetadata,proto3" json:"pair_metadata,omitempty"`
	Positions            []*Position       `protobuf:"bytes,6,rep,name=positions,proto3" json:"positions,omitempty"`
	PrepaidBadDebts      []*PrepaidBadDebt `protobuf:"bytes,7,rep,name=prepaid_bad_debts,json=prepaidBadDebts,proto3" json:"prepaid_bad_debts,omitempty"`
	WhitelistedAddresses []string          `protobuf:"bytes,8,rep,name=whitelisted_addresses,json=whitelistedAddresses,proto3" json:"whitelisted_addresses,omitempty"`
}

func (m *GenesisState) Reset()         { *m = GenesisState{} }
func (m *GenesisState) String() string { return proto.CompactTextString(m) }
func (*GenesisState) ProtoMessage()    {}
func (*GenesisState) Descriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{1}
}
func (m *GenesisState) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *GenesisState) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_GenesisState.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *GenesisState) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GenesisState.Merge(m, src)
}
func (m *GenesisState) XXX_Size() int {
	return m.Size()
}
func (m *GenesisState) XXX_DiscardUnknown() {
	xxx_messageInfo_GenesisState.DiscardUnknown(m)
}

var xxx_messageInfo_GenesisState proto.InternalMessageInfo

func (m *GenesisState) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

func (m *GenesisState) GetVaultBalance() []types.Coin {
	if m != nil {
		return m.VaultBalance
	}
	return nil
}

func (m *GenesisState) GetPerpEfBalance() []types.Coin {
	if m != nil {
		return m.PerpEfBalance
	}
	return nil
}

func (m *GenesisState) GetFeePoolBalance() []types.Coin {
	if m != nil {
		return m.FeePoolBalance
	}
	return nil
}

func (m *GenesisState) GetPairMetadata() []*PairMetadata {
	if m != nil {
		return m.PairMetadata
	}
	return nil
}

func (m *GenesisState) GetPositions() []*Position {
	if m != nil {
		return m.Positions
	}
	return nil
}

func (m *GenesisState) GetPrepaidBadDebts() []*PrepaidBadDebt {
	if m != nil {
		return m.PrepaidBadDebts
	}
	return nil
}

func (m *GenesisState) GetWhitelistedAddresses() []string {
	if m != nil {
		return m.WhitelistedAddresses
	}
	return nil
}

// Position identifies and records information on a user's position on one of
// the virtual liquidity pools.
type Position struct {
	// address identifies the address owner of this position
	TraderAddress github_com_cosmos_cosmos_sdk_types.AccAddress `protobuf:"bytes,1,opt,name=trader_address,json=traderAddress,proto3,casttype=github.com/cosmos/cosmos-sdk/types.AccAddress" json:"trader_address,omitempty"`
	// pair identifies the pair associated with this position
	Pair string `protobuf:"bytes,2,opt,name=pair,proto3" json:"pair,omitempty"`
	// Position size.
	Size_ github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=size,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"size"`
	// Amount of margin remaining in the position.
	Margin github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=margin,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"margin"`
	// OpenNotional is the quote denom value of the position when opening.
	// Used to calculate PnL.
	OpenNotional github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=open_notional,json=openNotional,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"open_notional"`
	// The last cumulative funding payment this position has applied.
	// Used to calculate the next funding payment.
	LastUpdateCumulativePremiumFraction github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=last_update_cumulative_premium_fraction,json=lastUpdateCumulativePremiumFraction,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"last_update_cumulative_premium_fraction"`
	// BlockNumber is the block number of the change to the position.
	BlockNumber int64 `protobuf:"varint,7,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`
}

func (m *Position) Reset()         { *m = Position{} }
func (m *Position) String() string { return proto.CompactTextString(m) }
func (*Position) ProtoMessage()    {}
func (*Position) Descriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{2}
}
func (m *Position) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Position) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Position.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Position) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Position.Merge(m, src)
}
func (m *Position) XXX_Size() int {
	return m.Size()
}
func (m *Position) XXX_DiscardUnknown() {
	xxx_messageInfo_Position.DiscardUnknown(m)
}

var xxx_messageInfo_Position proto.InternalMessageInfo

func (m *Position) GetTraderAddress() github_com_cosmos_cosmos_sdk_types.AccAddress {
	if m != nil {
		return m.TraderAddress
	}
	return nil
}

func (m *Position) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

func (m *Position) GetBlockNumber() int64 {
	if m != nil {
		return m.BlockNumber
	}
	return 0
}

type PositionResp struct {
	Position                  *Position                              `protobuf:"bytes,1,opt,name=position,proto3" json:"position,omitempty"`
	ExchangedQuoteAssetAmount github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,opt,name=exchanged_quote_asset_amount,json=exchangedQuoteAssetAmount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"exchanged_quote_asset_amount"`
	BadDebt                   github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,3,opt,name=bad_debt,json=badDebt,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"bad_debt"`
	ExchangedPositionSize     github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,4,opt,name=exchanged_position_size,json=exchangedPositionSize,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"exchanged_position_size"`
	FundingPayment            github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,5,opt,name=funding_payment,json=fundingPayment,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"funding_payment"`
	RealizedPnl               github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,6,opt,name=realized_pnl,json=realizedPnl,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"realized_pnl"`
	MarginToVault             github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,7,opt,name=margin_to_vault,json=marginToVault,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"margin_to_vault"`
	UnrealizedPnlAfter        github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,8,opt,name=unrealized_pnl_after,json=unrealizedPnlAfter,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"unrealized_pnl_after"`
}

func (m *PositionResp) Reset()         { *m = PositionResp{} }
func (m *PositionResp) String() string { return proto.CompactTextString(m) }
func (*PositionResp) ProtoMessage()    {}
func (*PositionResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{3}
}
func (m *PositionResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PositionResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PositionResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PositionResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PositionResp.Merge(m, src)
}
func (m *PositionResp) XXX_Size() int {
	return m.Size()
}
func (m *PositionResp) XXX_DiscardUnknown() {
	xxx_messageInfo_PositionResp.DiscardUnknown(m)
}

var xxx_messageInfo_PositionResp proto.InternalMessageInfo

func (m *PositionResp) GetPosition() *Position {
	if m != nil {
		return m.Position
	}
	return nil
}

type LiquidateResp struct {
	// Amount of bad debt created by the liquidation event
	BadDebt github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,1,opt,name=bad_debt,json=badDebt,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"bad_debt"`
	// Fee paid to the liquidator
	FeeToLiquidator github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=fee_to_liquidator,json=feeToLiquidator,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"fee_to_liquidator"`
	// Fee paid to the Perp EF fund
	FeeToPerpEcosystemFund github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,3,opt,name=fee_to_perp_ecosystem_fund,json=feeToPerpEcosystemFund,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"fee_to_perp_ecosystem_fund"`
	// Address of the liquidator
	Liquidator string `protobuf:"bytes,4,opt,name=liquidator,proto3" json:"liquidator,omitempty"`
	// Position response from the close or open reverse position
	PositionResp *PositionResp `protobuf:"bytes,5,opt,name=position_resp,json=positionResp,proto3" json:"position_resp,omitempty"`
}

func (m *LiquidateResp) Reset()         { *m = LiquidateResp{} }
func (m *LiquidateResp) String() string { return proto.CompactTextString(m) }
func (*LiquidateResp) ProtoMessage()    {}
func (*LiquidateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{4}
}
func (m *LiquidateResp) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *LiquidateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_LiquidateResp.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *LiquidateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LiquidateResp.Merge(m, src)
}
func (m *LiquidateResp) XXX_Size() int {
	return m.Size()
}
func (m *LiquidateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_LiquidateResp.DiscardUnknown(m)
}

var xxx_messageInfo_LiquidateResp proto.InternalMessageInfo

func (m *LiquidateResp) GetLiquidator() string {
	if m != nil {
		return m.Liquidator
	}
	return ""
}

func (m *LiquidateResp) GetPositionResp() *PositionResp {
	if m != nil {
		return m.PositionResp
	}
	return nil
}

type PairMetadata struct {
	Pair                       string                                   `protobuf:"bytes,1,opt,name=pair,proto3" json:"pair,omitempty"`
	CumulativePremiumFractions []github_com_cosmos_cosmos_sdk_types.Dec `protobuf:"bytes,2,rep,name=cumulative_premium_fractions,json=cumulativePremiumFractions,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Dec" json:"cumulative_premium_fractions"`
}

func (m *PairMetadata) Reset()         { *m = PairMetadata{} }
func (m *PairMetadata) String() string { return proto.CompactTextString(m) }
func (*PairMetadata) ProtoMessage()    {}
func (*PairMetadata) Descriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{5}
}
func (m *PairMetadata) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PairMetadata) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PairMetadata.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PairMetadata) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairMetadata.Merge(m, src)
}
func (m *PairMetadata) XXX_Size() int {
	return m.Size()
}
func (m *PairMetadata) XXX_DiscardUnknown() {
	xxx_messageInfo_PairMetadata.DiscardUnknown(m)
}

var xxx_messageInfo_PairMetadata proto.InternalMessageInfo

func (m *PairMetadata) GetPair() string {
	if m != nil {
		return m.Pair
	}
	return ""
}

type PrepaidBadDebt struct {
	Denom  string                                 `protobuf:"bytes,1,opt,name=denom,proto3" json:"denom,omitempty"`
	Amount github_com_cosmos_cosmos_sdk_types.Int `protobuf:"bytes,2,opt,name=amount,proto3,customtype=github.com/cosmos/cosmos-sdk/types.Int" json:"amount"`
}

func (m *PrepaidBadDebt) Reset()         { *m = PrepaidBadDebt{} }
func (m *PrepaidBadDebt) String() string { return proto.CompactTextString(m) }
func (*PrepaidBadDebt) ProtoMessage()    {}
func (*PrepaidBadDebt) Descriptor() ([]byte, []int) {
	return fileDescriptor_0416b6ef16ef80be, []int{6}
}
func (m *PrepaidBadDebt) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *PrepaidBadDebt) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_PrepaidBadDebt.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *PrepaidBadDebt) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PrepaidBadDebt.Merge(m, src)
}
func (m *PrepaidBadDebt) XXX_Size() int {
	return m.Size()
}
func (m *PrepaidBadDebt) XXX_DiscardUnknown() {
	xxx_messageInfo_PrepaidBadDebt.DiscardUnknown(m)
}

var xxx_messageInfo_PrepaidBadDebt proto.InternalMessageInfo

func (m *PrepaidBadDebt) GetDenom() string {
	if m != nil {
		return m.Denom
	}
	return ""
}

func init() {
	proto.RegisterEnum("nibiru.perp.v1.Side", Side_name, Side_value)
	proto.RegisterEnum("nibiru.perp.v1.PnLCalcOption", PnLCalcOption_name, PnLCalcOption_value)
	proto.RegisterEnum("nibiru.perp.v1.PnLPreferenceOption", PnLPreferenceOption_name, PnLPreferenceOption_value)
	proto.RegisterEnum("nibiru.perp.v1.MarginCalculationPriceOption", MarginCalculationPriceOption_name, MarginCalculationPriceOption_value)
	proto.RegisterType((*Params)(nil), "nibiru.perp.v1.Params")
	proto.RegisterType((*GenesisState)(nil), "nibiru.perp.v1.GenesisState")
	proto.RegisterType((*Position)(nil), "nibiru.perp.v1.Position")
	proto.RegisterType((*PositionResp)(nil), "nibiru.perp.v1.PositionResp")
	proto.RegisterType((*LiquidateResp)(nil), "nibiru.perp.v1.LiquidateResp")
	proto.RegisterType((*PairMetadata)(nil), "nibiru.perp.v1.PairMetadata")
	proto.RegisterType((*PrepaidBadDebt)(nil), "nibiru.perp.v1.PrepaidBadDebt")
}

func init() { proto.RegisterFile("perp/v1/state.proto", fileDescriptor_0416b6ef16ef80be) }

var fileDescriptor_0416b6ef16ef80be = []byte{
	// 1340 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x97, 0x4f, 0x6f, 0x13, 0x49,
	0x16, 0xc0, 0xe3, 0xd8, 0xf9, 0xf7, 0x62, 0x27, 0xa6, 0x08, 0xe0, 0x64, 0x83, 0x93, 0xf5, 0x6a,
	0x97, 0x28, 0x2b, 0x6c, 0x05, 0xd0, 0x1e, 0xb8, 0xd9, 0x8e, 0x83, 0xbc, 0x72, 0x9c, 0xa6, 0x9d,
	0x40, 0x96, 0x4b, 0x6d, 0xb9, 0xfb, 0x39, 0x69, 0xe8, 0xae, 0x6a, 0xba, 0xaa, 0xb3, 0x84, 0xeb,
	0xee, 0xde, 0xe7, 0x30, 0xdf, 0x64, 0xbe, 0x04, 0xa7, 0x11, 0xc7, 0xd1, 0x1c, 0xa2, 0x11, 0x7c,
	0x83, 0x39, 0x8e, 0x34, 0xd2, 0xa8, 0xaa, 0xdb, 0x8e, 0x19, 0x60, 0x34, 0xf1, 0x70, 0x72, 0x57,
	0xd5, 0x7b, 0xbf, 0xf7, 0xfa, 0xd5, 0xfb, 0xe3, 0x86, 0xeb, 0x21, 0x46, 0x61, 0xed, 0x6c, 0xa7,
	0x26, 0x15, 0x53, 0x58, 0x0d, 0x23, 0xa1, 0x04, 0x59, 0xe2, 0x5e, 0xdf, 0x8b, 0xe2, 0xaa, 0x3e,
	0xab, 0x9e, 0xed, 0xac, 0xad, 0x9c, 0x88, 0x13, 0x61, 0x8e, 0x6a, 0xfa, 0x29, 0x91, 0x5a, 0x2b,
	0x3b, 0x42, 0x06, 0x42, 0xd6, 0xfa, 0x4c, 0x62, 0xed, 0x6c, 0xa7, 0x8f, 0x8a, 0xed, 0xd4, 0x1c,
	0xe1, 0xf1, 0xf4, 0x7c, 0x35, 0x39, 0xa7, 0x89, 0x62, 0xb2, 0x48, 0x8e, 0x2a, 0xdf, 0x4c, 0xc3,
	0xac, 0xc5, 0x22, 0x16, 0x48, 0x52, 0x82, 0x39, 0xa9, 0x44, 0x18, 0xa2, 0x5b, 0xca, 0x6c, 0x66,
	0xb6, 0xe6, 0xed, 0xe1, 0x92, 0x9c, 0x42, 0x29, 0x60, 0x1e, 0x57, 0xc8, 0x19, 0x77, 0x90, 0x06,
	0x2c, 0x3a, 0xf1, 0x38, 0x8d, 0x98, 0xf2, 0x44, 0x69, 0x7a, 0x33, 0xb3, 0xb5, 0xd0, 0xa8, 0xbe,
	0xb9, 0xd8, 0x98, 0xfa, 0xfe, 0x62, 0xe3, 0x6f, 0x27, 0x9e, 0x3a, 0x8d, 0xfb, 0x55, 0x47, 0x04,
	0xa9, 0x9d, 0xf4, 0xe7, 0xae, 0x74, 0x5f, 0xd4, 0xd4, 0x79, 0x88, 0xb2, 0xba, 0x8b, 0x8e, 0x7d,
	0x73, 0x8c, 0xb7, 0x6f, 0x70, 0xb6, 0xa6, 0x91, 0xdb, 0x00, 0x4a, 0xf8, 0x7e, 0xca, 0xce, 0x6e,
	0x66, 0xb6, 0xb2, 0xf6, 0x82, 0xde, 0x49, 0x8e, 0xff, 0x0c, 0x79, 0x19, 0x46, 0xc8, 0xdc, 0x54,
	0x20, 0x67, 0x04, 0x16, 0x93, 0xbd, 0x44, 0xe4, 0x0e, 0x2c, 0xfb, 0xde, 0xcb, 0xd8, 0x73, 0xf5,
	0x8a, 0xd3, 0x01, 0x62, 0x69, 0xc6, 0x48, 0x2d, 0x8d, 0x6d, 0xef, 0x21, 0x92, 0x87, 0xb0, 0x1a,
	0xb2, 0x48, 0x79, 0xcc, 0xa7, 0xe3, 0x0a, 0x09, 0x78, 0xd6, 0xa8, 0xdc, 0x4a, 0x05, 0x3a, 0x97,
	0xe7, 0xc6, 0x48, 0xe5, 0xe7, 0x1c, 0xe4, 0x1f, 0x21, 0x47, 0xe9, 0xc9, 0x9e, 0xbe, 0x2d, 0xf2,
	0x00, 0x66, 0x43, 0x13, 0x45, 0x13, 0xba, 0xc5, 0x7b, 0x37, 0xab, 0x1f, 0x5e, 0x5c, 0x35, 0x89,
	0x71, 0x23, 0xa7, 0xe3, 0x64, 0xa7, 0xb2, 0x04, 0xa1, 0x70, 0xc6, 0x62, 0x5f, 0xd1, 0x3e, 0xf3,
	0x75, 0x24, 0x4a, 0xd3, 0x9b, 0xd9, 0xad, 0xc5, 0x7b, 0xab, 0xd5, 0xf4, 0x8a, 0xf4, 0x7d, 0x56,
	0xd3, 0xfb, 0xac, 0x36, 0x85, 0xc7, 0x1b, 0x7f, 0xd5, 0xfa, 0x3f, 0x5e, 0x6c, 0xdc, 0x3e, 0x67,
	0x81, 0xff, 0xb0, 0x12, 0x08, 0x37, 0xf6, 0x91, 0x32, 0xc7, 0x11, 0x31, 0x1f, 0x61, 0x2a, 0x76,
	0xde, 0x60, 0x1b, 0xc9, 0x92, 0x9c, 0xc2, 0xb2, 0x76, 0x83, 0xe2, 0x60, 0x64, 0x28, 0xfb, 0x85,
	0x0c, 0x15, 0x34, 0xb8, 0x35, 0x18, 0x5a, 0x7a, 0x0e, 0xc5, 0x01, 0x22, 0x0d, 0x85, 0xf0, 0x47,
	0xa6, 0x72, 0x5f, 0xc8, 0xd4, 0xd2, 0x00, 0xd1, 0x12, 0xc2, 0x1f, 0xda, 0xaa, 0x43, 0x21, 0x64,
	0x5e, 0x44, 0x03, 0x54, 0xcc, 0x65, 0x8a, 0x95, 0x66, 0x8c, 0xa1, 0xf5, 0x8f, 0x23, 0xef, 0x45,
	0xfb, 0xa9, 0x8c, 0x9d, 0x0f, 0xc7, 0x56, 0xe4, 0x1f, 0xb0, 0x10, 0x0a, 0xe9, 0xe9, 0x7b, 0x95,
	0xa5, 0x59, 0xa3, 0x5e, 0xfa, 0x48, 0x3d, 0x15, 0xb0, 0x2f, 0x45, 0xc9, 0x3f, 0xe1, 0x5a, 0x18,
	0x61, 0xc8, 0x3c, 0x97, 0xf6, 0x99, 0x4b, 0x5d, 0xec, 0x2b, 0x59, 0x9a, 0x33, 0xfa, 0xe5, 0x8f,
	0xf4, 0x13, 0xc1, 0x06, 0x73, 0x77, 0xb1, 0xaf, 0xec, 0xe5, 0xf0, 0x83, 0xb5, 0x24, 0xf7, 0xe1,
	0xc6, 0x7f, 0x4e, 0x3d, 0x85, 0xbe, 0x27, 0x15, 0xba, 0x94, 0xb9, 0x6e, 0x84, 0x52, 0xa2, 0x2c,
	0xcd, 0x6f, 0x66, 0xb7, 0x16, 0xec, 0x95, 0xb1, 0xc3, 0xfa, 0xf0, 0xac, 0xf2, 0xdf, 0x1c, 0xcc,
	0x0f, 0x1d, 0x23, 0xc7, 0xb0, 0xa4, 0x22, 0xe6, 0x62, 0x34, 0x54, 0x36, 0x39, 0x98, 0x6f, 0xec,
	0xfc, 0x74, 0xb1, 0x71, 0xf7, 0x77, 0xd4, 0x63, 0xdd, 0x71, 0x52, 0xb2, 0x5d, 0x48, 0x40, 0xe9,
	0x92, 0x10, 0xc8, 0xe9, 0x78, 0x25, 0x35, 0x6e, 0x9b, 0x67, 0xd2, 0x80, 0x9c, 0xf4, 0x5e, 0xa3,
	0xa9, 0xcd, 0xab, 0xd7, 0xbd, 0xd1, 0x25, 0x7b, 0x30, 0x9b, 0xf4, 0x10, 0x53, 0xc0, 0x57, 0xa7,
	0xa4, 0xda, 0xa4, 0x07, 0x05, 0x11, 0x22, 0xa7, 0x5c, 0xe8, 0x40, 0x30, 0xdf, 0x54, 0xfa, 0xd5,
	0x71, 0x79, 0x0d, 0xe9, 0xa6, 0x0c, 0xf2, 0xbf, 0x0c, 0xdc, 0xf1, 0x99, 0x54, 0x34, 0x0e, 0x5d,
	0xa6, 0x90, 0x3a, 0x71, 0x10, 0xfb, 0x4c, 0x79, 0x67, 0x48, 0xc3, 0x08, 0x03, 0x2f, 0x0e, 0xe8,
	0x20, 0x62, 0x8e, 0x96, 0x36, 0x6d, 0xe2, 0xea, 0xf6, 0xfe, 0xa2, 0xf1, 0x47, 0x86, 0xde, 0x1c,
	0xc1, 0xad, 0x84, 0xbd, 0x97, 0xa2, 0x75, 0xab, 0xeb, 0xfb, 0xc2, 0x79, 0x41, 0x79, 0x1c, 0xf4,
	0x31, 0x2a, 0xcd, 0x25, 0xad, 0xce, 0xec, 0x75, 0xcd, 0x56, 0xe5, 0xdb, 0x19, 0xc8, 0x8f, 0xd2,
	0x13, 0x65, 0x48, 0x1e, 0xc0, 0xfc, 0x30, 0x49, 0xd3, 0x3e, 0xf4, 0xf9, 0x74, 0x1e, 0x49, 0x12,
	0x01, 0xeb, 0xf8, 0xca, 0x39, 0x65, 0xfc, 0x04, 0x5d, 0xfa, 0x32, 0x16, 0x0a, 0x29, 0x93, 0x12,
	0x15, 0x65, 0x81, 0xae, 0xc0, 0x09, 0x3b, 0xfc, 0xea, 0x88, 0xf9, 0x58, 0x23, 0xeb, 0x9a, 0x58,
	0x37, 0x40, 0xd2, 0x86, 0xf9, 0x61, 0xd9, 0x4c, 0x98, 0x46, 0x73, 0xfd, 0xa4, 0x7c, 0xc8, 0x00,
	0x6e, 0x5d, 0xfa, 0x3e, 0x7c, 0x23, 0x6a, 0x12, 0x74, 0xb2, 0xd4, 0xba, 0x31, 0xc2, 0x0d, 0x23,
	0xd5, 0xd3, 0x19, 0xfb, 0x14, 0x96, 0x07, 0x31, 0x77, 0x3d, 0x7e, 0x42, 0x43, 0x76, 0x1e, 0x20,
	0x57, 0x13, 0xe6, 0xda, 0x52, 0x8a, 0xb1, 0x12, 0x0a, 0x79, 0x0c, 0xf9, 0x08, 0x99, 0xef, 0xbd,
	0xd6, 0xfe, 0x73, 0x7f, 0xc2, 0x8c, 0x5a, 0x1c, 0x32, 0x2c, 0xee, 0x93, 0x27, 0xb0, 0x9c, 0x4e,
	0x68, 0x25, 0xa8, 0x19, 0x04, 0x26, 0x79, 0xae, 0x4e, 0x2d, 0x24, 0x98, 0x43, 0xf1, 0x44, 0x43,
	0xc8, 0xbf, 0x61, 0x25, 0xe6, 0xe3, 0xce, 0x52, 0x36, 0x50, 0x18, 0x95, 0xe6, 0x27, 0x82, 0x93,
	0x4b, 0x96, 0xc5, 0xfd, 0xba, 0x26, 0x55, 0xfe, 0x9f, 0x85, 0xc2, 0x70, 0xd6, 0xa2, 0xc9, 0xe8,
	0xf1, 0x54, 0xc9, 0xfc, 0xb1, 0x54, 0x79, 0x06, 0xd7, 0xf4, 0x6c, 0x52, 0x62, 0x34, 0xee, 0x45,
	0x34, 0x41, 0x6e, 0xb7, 0xb9, 0xb2, 0x97, 0x07, 0x88, 0x87, 0xa2, 0x33, 0xc2, 0x90, 0xe7, 0xb0,
	0x96, 0xb2, 0x93, 0x41, 0xeb, 0x08, 0x79, 0x2e, 0x15, 0x06, 0x54, 0xdf, 0xf6, 0x04, 0x39, 0xae,
	0x8d, 0xdc, 0x34, 0x46, 0x2c, 0x3d, 0x5f, 0x87, 0xb8, 0xbd, 0x98, 0xbb, 0xa4, 0x0c, 0x30, 0xf6,
	0x02, 0x26, 0xcb, 0xed, 0xb1, 0x1d, 0x33, 0x17, 0x87, 0x85, 0x10, 0xa1, 0x0c, 0x4d, 0xa2, 0x7e,
	0x6a, 0x2e, 0x8e, 0x75, 0x0e, 0x3b, 0x1f, 0x8e, 0xad, 0x2a, 0x5f, 0x67, 0x20, 0x3f, 0x3e, 0x36,
	0x47, 0x83, 0x20, 0x33, 0x36, 0x08, 0x42, 0x58, 0xff, 0x8d, 0xd6, 0x28, 0xcd, 0x7f, 0x99, 0xab,
	0x5f, 0xd7, 0x9a, 0xf3, 0xb9, 0x8e, 0x28, 0x2b, 0x1c, 0x96, 0x3e, 0x9c, 0xa6, 0x64, 0x05, 0x66,
	0x5c, 0xe4, 0x22, 0x48, 0x1d, 0x4b, 0x16, 0x7a, 0xbc, 0x4c, 0xdc, 0xba, 0x74, 0xe4, 0x53, 0xed,
	0xed, 0x1a, 0xe4, 0x7a, 0x9e, 0x8b, 0x64, 0x05, 0x8a, 0xbd, 0xf6, 0x6e, 0x8b, 0x1e, 0x75, 0x7b,
	0x56, 0xab, 0xd9, 0xde, 0x6b, 0xb7, 0x76, 0x8b, 0x53, 0x64, 0x0e, 0xb2, 0x8d, 0xa3, 0x7f, 0x15,
	0x33, 0x64, 0x1e, 0x72, 0xbd, 0x56, 0xa7, 0x53, 0x9c, 0xde, 0x7e, 0x02, 0x05, 0x8b, 0x77, 0x9a,
	0xcc, 0x77, 0x0e, 0x42, 0xd3, 0x5a, 0x37, 0xe0, 0x4f, 0x56, 0xb7, 0x43, 0x9b, 0xf5, 0x4e, 0x93,
	0x1e, 0x58, 0x87, 0xed, 0x83, 0xee, 0xaf, 0x20, 0x4b, 0x00, 0x3d, 0xeb, 0xe0, 0x90, 0x5a, 0x76,
	0xbb, 0xd9, 0x4a, 0x58, 0x87, 0x4f, 0xeb, 0x56, 0x71, 0x9a, 0x00, 0xcc, 0x1e, 0xd8, 0xf5, 0x66,
	0xa7, 0x55, 0xcc, 0x6e, 0x3f, 0x82, 0xeb, 0x16, 0xef, 0x58, 0x11, 0x0e, 0x30, 0x42, 0xee, 0x60,
	0x4a, 0x2f, 0xc3, 0x9a, 0xa6, 0x5b, 0x76, 0x6b, 0xaf, 0x65, 0xb7, 0xba, 0xcd, 0x4f, 0x78, 0xb8,
	0x5f, 0x3f, 0x2e, 0x66, 0xcc, 0x43, 0xbb, 0x5b, 0x9c, 0xde, 0x7e, 0x09, 0xeb, 0xc9, 0xbf, 0x6d,
	0xed, 0xa3, 0x09, 0xb3, 0xe0, 0x56, 0xe4, 0x8d, 0x88, 0x35, 0xf8, 0xfb, 0x7e, 0xdd, 0x7e, 0xd4,
	0xee, 0x1a, 0x97, 0x8f, 0x3a, 0x75, 0xe3, 0xb2, 0x71, 0xee, 0xd3, 0xfe, 0xeb, 0x77, 0xb7, 0x0e,
	0x0e, 0x8b, 0x19, 0xb2, 0x00, 0x33, 0xed, 0xee, 0x6e, 0xeb, 0xb8, 0x38, 0x4d, 0x16, 0x61, 0x6e,
	0xbf, 0x7e, 0x4c, 0xad, 0x6e, 0xa7, 0x98, 0x6d, 0xec, 0xbe, 0x79, 0x57, 0xce, 0xbc, 0x7d, 0x57,
	0xce, 0xfc, 0xf0, 0xae, 0x9c, 0xf9, 0xea, 0x7d, 0x79, 0xea, 0xed, 0xfb, 0xf2, 0xd4, 0x77, 0xef,
	0xcb, 0x53, 0xcf, 0xb6, 0xc7, 0xae, 0xa3, 0x6b, 0x72, 0xb3, 0x79, 0xca, 0x3c, 0x5e, 0x4b, 0xf2,
	0xb4, 0xf6, 0xaa, 0x66, 0x3e, 0x88, 0xcc, 0xb5, 0xf4, 0x67, 0xcd, 0xd7, 0xca, 0xfd, 0x5f, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x5f, 0x8a, 0x52, 0x50, 0x25, 0x0d, 0x00, 0x00,
}

func (m *Params) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Params) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Params) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PartialLiquidationRatio != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.PartialLiquidationRatio))
		i--
		dAtA[i] = 0x30
	}
	if m.LiquidationFee != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.LiquidationFee))
		i--
		dAtA[i] = 0x28
	}
	if m.SpreadRatio != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.SpreadRatio))
		i--
		dAtA[i] = 0x20
	}
	if m.TollRatio != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.TollRatio))
		i--
		dAtA[i] = 0x18
	}
	{
		size := m.MaintenanceMarginRatio.Size()
		i -= size
		if _, err := m.MaintenanceMarginRatio.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Stopped {
		i--
		if m.Stopped {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *GenesisState) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *GenesisState) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *GenesisState) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.WhitelistedAddresses) > 0 {
		for iNdEx := len(m.WhitelistedAddresses) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.WhitelistedAddresses[iNdEx])
			copy(dAtA[i:], m.WhitelistedAddresses[iNdEx])
			i = encodeVarintState(dAtA, i, uint64(len(m.WhitelistedAddresses[iNdEx])))
			i--
			dAtA[i] = 0x42
		}
	}
	if len(m.PrepaidBadDebts) > 0 {
		for iNdEx := len(m.PrepaidBadDebts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PrepaidBadDebts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x3a
		}
	}
	if len(m.Positions) > 0 {
		for iNdEx := len(m.Positions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Positions[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if len(m.PairMetadata) > 0 {
		for iNdEx := len(m.PairMetadata) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PairMetadata[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if len(m.FeePoolBalance) > 0 {
		for iNdEx := len(m.FeePoolBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.FeePoolBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x22
		}
	}
	if len(m.PerpEfBalance) > 0 {
		for iNdEx := len(m.PerpEfBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.PerpEfBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if len(m.VaultBalance) > 0 {
		for iNdEx := len(m.VaultBalance) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.VaultBalance[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *Position) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Position) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Position) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BlockNumber != 0 {
		i = encodeVarintState(dAtA, i, uint64(m.BlockNumber))
		i--
		dAtA[i] = 0x38
	}
	{
		size := m.LastUpdateCumulativePremiumFraction.Size()
		i -= size
		if _, err := m.LastUpdateCumulativePremiumFraction.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.OpenNotional.Size()
		i -= size
		if _, err := m.OpenNotional.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.Margin.Size()
		i -= size
		if _, err := m.Margin.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.Size_.Size()
		i -= size
		if _, err := m.Size_.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	if len(m.Pair) > 0 {
		i -= len(m.Pair)
		copy(dAtA[i:], m.Pair)
		i = encodeVarintState(dAtA, i, uint64(len(m.Pair)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TraderAddress) > 0 {
		i -= len(m.TraderAddress)
		copy(dAtA[i:], m.TraderAddress)
		i = encodeVarintState(dAtA, i, uint64(len(m.TraderAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PositionResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PositionResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PositionResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.UnrealizedPnlAfter.Size()
		i -= size
		if _, err := m.UnrealizedPnlAfter.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x42
	{
		size := m.MarginToVault.Size()
		i -= size
		if _, err := m.MarginToVault.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x3a
	{
		size := m.RealizedPnl.Size()
		i -= size
		if _, err := m.RealizedPnl.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x32
	{
		size := m.FundingPayment.Size()
		i -= size
		if _, err := m.FundingPayment.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x2a
	{
		size := m.ExchangedPositionSize.Size()
		i -= size
		if _, err := m.ExchangedPositionSize.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x22
	{
		size := m.BadDebt.Size()
		i -= size
		if _, err := m.BadDebt.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.ExchangedQuoteAssetAmount.Size()
		i -= size
		if _, err := m.ExchangedQuoteAssetAmount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if m.Position != nil {
		{
			size, err := m.Position.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintState(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *LiquidateResp) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *LiquidateResp) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *LiquidateResp) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.PositionResp != nil {
		{
			size, err := m.PositionResp.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintState(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x2a
	}
	if len(m.Liquidator) > 0 {
		i -= len(m.Liquidator)
		copy(dAtA[i:], m.Liquidator)
		i = encodeVarintState(dAtA, i, uint64(len(m.Liquidator)))
		i--
		dAtA[i] = 0x22
	}
	{
		size := m.FeeToPerpEcosystemFund.Size()
		i -= size
		if _, err := m.FeeToPerpEcosystemFund.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x1a
	{
		size := m.FeeToLiquidator.Size()
		i -= size
		if _, err := m.FeeToLiquidator.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	{
		size := m.BadDebt.Size()
		i -= size
		if _, err := m.BadDebt.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *PairMetadata) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PairMetadata) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PairMetadata) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.CumulativePremiumFractions) > 0 {
		for iNdEx := len(m.CumulativePremiumFractions) - 1; iNdEx >= 0; iNdEx-- {
			{
				size := m.CumulativePremiumFractions[iNdEx].Size()
				i -= size
				if _, err := m.CumulativePremiumFractions[iNdEx].MarshalTo(dAtA[i:]); err != nil {
					return 0, err
				}
				i = encodeVarintState(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x12
		}
	}
	if len(m.Pair) > 0 {
		i -= len(m.Pair)
		copy(dAtA[i:], m.Pair)
		i = encodeVarintState(dAtA, i, uint64(len(m.Pair)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *PrepaidBadDebt) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *PrepaidBadDebt) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *PrepaidBadDebt) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size := m.Amount.Size()
		i -= size
		if _, err := m.Amount.MarshalTo(dAtA[i:]); err != nil {
			return 0, err
		}
		i = encodeVarintState(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Denom) > 0 {
		i -= len(m.Denom)
		copy(dAtA[i:], m.Denom)
		i = encodeVarintState(dAtA, i, uint64(len(m.Denom)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintState(dAtA []byte, offset int, v uint64) int {
	offset -= sovState(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Params) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Stopped {
		n += 2
	}
	l = m.MaintenanceMarginRatio.Size()
	n += 1 + l + sovState(uint64(l))
	if m.TollRatio != 0 {
		n += 1 + sovState(uint64(m.TollRatio))
	}
	if m.SpreadRatio != 0 {
		n += 1 + sovState(uint64(m.SpreadRatio))
	}
	if m.LiquidationFee != 0 {
		n += 1 + sovState(uint64(m.LiquidationFee))
	}
	if m.PartialLiquidationRatio != 0 {
		n += 1 + sovState(uint64(m.PartialLiquidationRatio))
	}
	return n
}

func (m *GenesisState) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovState(uint64(l))
	if len(m.VaultBalance) > 0 {
		for _, e := range m.VaultBalance {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.PerpEfBalance) > 0 {
		for _, e := range m.PerpEfBalance {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.FeePoolBalance) > 0 {
		for _, e := range m.FeePoolBalance {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.PairMetadata) > 0 {
		for _, e := range m.PairMetadata {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.Positions) > 0 {
		for _, e := range m.Positions {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.PrepaidBadDebts) > 0 {
		for _, e := range m.PrepaidBadDebts {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	if len(m.WhitelistedAddresses) > 0 {
		for _, s := range m.WhitelistedAddresses {
			l = len(s)
			n += 1 + l + sovState(uint64(l))
		}
	}
	return n
}

func (m *Position) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TraderAddress)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = len(m.Pair)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = m.Size_.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.Margin.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.OpenNotional.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.LastUpdateCumulativePremiumFraction.Size()
	n += 1 + l + sovState(uint64(l))
	if m.BlockNumber != 0 {
		n += 1 + sovState(uint64(m.BlockNumber))
	}
	return n
}

func (m *PositionResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Position != nil {
		l = m.Position.Size()
		n += 1 + l + sovState(uint64(l))
	}
	l = m.ExchangedQuoteAssetAmount.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.BadDebt.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.ExchangedPositionSize.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.FundingPayment.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.RealizedPnl.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.MarginToVault.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.UnrealizedPnlAfter.Size()
	n += 1 + l + sovState(uint64(l))
	return n
}

func (m *LiquidateResp) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.BadDebt.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.FeeToLiquidator.Size()
	n += 1 + l + sovState(uint64(l))
	l = m.FeeToPerpEcosystemFund.Size()
	n += 1 + l + sovState(uint64(l))
	l = len(m.Liquidator)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if m.PositionResp != nil {
		l = m.PositionResp.Size()
		n += 1 + l + sovState(uint64(l))
	}
	return n
}

func (m *PairMetadata) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Pair)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	if len(m.CumulativePremiumFractions) > 0 {
		for _, e := range m.CumulativePremiumFractions {
			l = e.Size()
			n += 1 + l + sovState(uint64(l))
		}
	}
	return n
}

func (m *PrepaidBadDebt) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Denom)
	if l > 0 {
		n += 1 + l + sovState(uint64(l))
	}
	l = m.Amount.Size()
	n += 1 + l + sovState(uint64(l))
	return n
}

func sovState(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozState(x uint64) (n int) {
	return sovState(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Params) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Params: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Params: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Stopped", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Stopped = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MaintenanceMarginRatio", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MaintenanceMarginRatio.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TollRatio", wireType)
			}
			m.TollRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TollRatio |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SpreadRatio", wireType)
			}
			m.SpreadRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SpreadRatio |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field LiquidationFee", wireType)
			}
			m.LiquidationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.LiquidationFee |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field PartialLiquidationRatio", wireType)
			}
			m.PartialLiquidationRatio = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.PartialLiquidationRatio |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *GenesisState) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: GenesisState: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: GenesisState: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field VaultBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.VaultBalance = append(m.VaultBalance, types.Coin{})
			if err := m.VaultBalance[len(m.VaultBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PerpEfBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PerpEfBalance = append(m.PerpEfBalance, types.Coin{})
			if err := m.PerpEfBalance[len(m.PerpEfBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePoolBalance", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.FeePoolBalance = append(m.FeePoolBalance, types.Coin{})
			if err := m.FeePoolBalance[len(m.FeePoolBalance)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PairMetadata", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PairMetadata = append(m.PairMetadata, &PairMetadata{})
			if err := m.PairMetadata[len(m.PairMetadata)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Positions", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Positions = append(m.Positions, &Position{})
			if err := m.Positions[len(m.Positions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PrepaidBadDebts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.PrepaidBadDebts = append(m.PrepaidBadDebts, &PrepaidBadDebt{})
			if err := m.PrepaidBadDebts[len(m.PrepaidBadDebts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field WhitelistedAddresses", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.WhitelistedAddresses = append(m.WhitelistedAddresses, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Position) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Position: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Position: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TraderAddress", wireType)
			}
			var byteLen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				byteLen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if byteLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + byteLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TraderAddress = append(m.TraderAddress[:0], dAtA[iNdEx:postIndex]...)
			if m.TraderAddress == nil {
				m.TraderAddress = []byte{}
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Size_", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Size_.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Margin", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Margin.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OpenNotional", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.OpenNotional.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field LastUpdateCumulativePremiumFraction", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.LastUpdateCumulativePremiumFraction.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BlockNumber", wireType)
			}
			m.BlockNumber = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BlockNumber |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PositionResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PositionResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PositionResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Position", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Position == nil {
				m.Position = &Position{}
			}
			if err := m.Position.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangedQuoteAssetAmount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExchangedQuoteAssetAmount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BadDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BadDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ExchangedPositionSize", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.ExchangedPositionSize.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FundingPayment", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FundingPayment.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RealizedPnl", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.RealizedPnl.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 7:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MarginToVault", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.MarginToVault.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 8:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field UnrealizedPnlAfter", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.UnrealizedPnlAfter.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *LiquidateResp) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: LiquidateResp: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: LiquidateResp: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BadDebt", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.BadDebt.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeToLiquidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeToLiquidator.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeToPerpEcosystemFund", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.FeeToPerpEcosystemFund.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Liquidator", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Liquidator = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field PositionResp", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.PositionResp == nil {
				m.PositionResp = &PositionResp{}
			}
			if err := m.PositionResp.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PairMetadata) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PairMetadata: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PairMetadata: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Pair", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Pair = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field CumulativePremiumFractions", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			var v github_com_cosmos_cosmos_sdk_types.Dec
			m.CumulativePremiumFractions = append(m.CumulativePremiumFractions, v)
			if err := m.CumulativePremiumFractions[len(m.CumulativePremiumFractions)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *PrepaidBadDebt) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowState
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: PrepaidBadDebt: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: PrepaidBadDebt: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Denom", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Denom = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowState
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthState
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthState
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Amount.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipState(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthState
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipState(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowState
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowState
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthState
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupState
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthState
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthState        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowState          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupState = fmt.Errorf("proto: unexpected end of group")
)
