# Displays available recipes by running `just -l`.
setup:
  #!/usr/bin/env bash
  just -l

# Generate protobuf-based types in Golang
gen-proto-go:
  #!/usr/bin/env bash
  echo "Generating protobuf-based types in Go"
  if ! bash contrib/scripts/gen-proto-go.sh; then
    echo "❌ failed to generate Go types from protobuf"
    exit 1
  fi
  echo "✅ SUCCESS: just gen-proto-go"

# Run cosmos-sdk tests relevant to Nibiru
test:
  #!/usr/bin/env bash
  printf "\n\nRun tests - cosmos-sdk/types:\n"
  go test ./types/... -tags='ledger test_ledger_mock'

  printf "\n\nRun tests - cosmos-sdk/x:\n"
  go test ./x/...

  printf "\n\nRun tests - cosmos-sdk/baseapp:\n"
  go test ./baseapp/...
