have_fun: true
code_review:
  disable: false
  comment_severity_threshold: MEDIUM
  max_review_comments: -1
  pull_request_opened:
    help: false
    summary: false
    code_review: true
    include_drafts: true
# ignore_patterns: Acceptable Glob patterns:
# https://code.visualstudio.com/docs/editor/glob-patterns
ignore_patterns: ["**/*.pb.go", "x/evm/embeds/abi/*", "api/*", "node_modules"]
