# Use this justfile by
# (1) installing with "cargo install just"
# (2) running the "just" command.

# Displays available recipes by running `just -l`.
setup:
    #!/usr/bin/env bash
    just -l

# Install all dependencies
install:
    #!/usr/bin/env bash
    bun install --frozen-lockfile
    (cd passkey-sdk && bun install --frozen-lockfile)
    just gen-types

compile:
    bun run hardhat compile

deploy-passkey:
    bun scripts/passkey-demo-setup.js

bundler:
    bun run bundler

# Runs the E2E tests
test *args:
    #!/usr/bin/env bash
    set -euo pipefail
    just gen-types
    bun test {{ args }}

# Runs tx receipt tests. Used for testnet quick check.
test-basic:
    #!/usr/bin/env bash
    set -euo pipefail
    bun test -- tx_receipt.test.ts

# Format
fmt:
    bun run prettier --write . --config prettier.config.js

# Format (check only)
fmt-check:
    bun run prettier --check . --config prettier.config.js

gen-types:
    bun run hardhat typechain
