name: EVM E2E Basic Testnet (Scheduled)

on:
  schedule:
    - cron: "0 * * * *"  # every hour at 00 min

jobs:
  e2e-evm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: "just install"
        run: just install
        working-directory: "evm-e2e"

      - name: "Run tests (just test-basic)"
        run: just test-basic
        working-directory: "evm-e2e"
        env:
          JSON_RPC_ENDPOINT: https://evm-rpc.testnet-1.nibiru.fi
          MNEMONIC: ${{ secrets.WALLET_MNEMONIC_TESTNET }}

      - name: Send failure to slack channel
        if: always()
        uses: ravsamhq/notify-slack-action@v2
        with:
          status: ${{ job.status }}
          notify_when: "failure"
          notification_title: "EVM basic tests failed on Testnet"
          message_format: "{emoji} *{workflow}* {status_message} Run: {run_url}"
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_TESTNET }}
