name: Run short simulations

on:
  pull_request:
    paths: ["**.go", "**.proto", "go.mod", "go.sum"]

jobs:
  install-runsim:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
      - name: Install runsim
        run: go install github.com/cosmos/tools/cmd/runsim@v1.0.0

  test-sim-nondeterminism:
    runs-on: ubuntu-latest
    needs: [install-runsim]
    steps:
      - uses: actions/checkout@v4
      - uses: technote-space/get-diff-action@v6
        with:
          SUFFIX_FILTER: |
            **/**.go
            go.mod
            go.sum
      - uses: actions/setup-go@v4
        with:
          go-version: 1.19
          cache: true
        if: env.GIT_DIFF
      - uses: actions/cache@v3
        with:
          path: ~/go/bin
          key: ${{ runner.os }}-go-runsim-binary
        if: env.GIT_DIFF
      - name: test-sim-nondeterminism
        run: |
          make test-sim-nondeterminism
        if: env.GIT_DIFF
